apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pokeshop-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/devshah95/PokeDex-Live.git
    targetRevision: develop
    path: kubernetes/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: pokeshop-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
