sonar.projectKey=pokeshop-pokemon-service
sonar.projectName=PokéShop Pokemon Service
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=src/tests
sonar.exclusions=node_modules/**,coverage/**,src/tests/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=http://localhost:9000
